name: Build
on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  jar:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Build
      run: make
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Heart-${{ github.sha }}
        path: ${{ github.workspace }}/bin/Heart.jar
